### ISSUE TITLE
Modificar Leémes.

### ISSUE THREAD

**Issue by fizzvr** [DesarrolloWebNodeJS/Exchange#1]
Update leémes al español.

**Comment by adriceci** [comment]
Ya he subido los README en Español y correctamente formateado, si puedes revisarlo y dejamos el tema solucionado.

**Comment by Israel-Laguan** [comment]
Me parece que el tema de traducción esta solucionado, como menciona [Ceci98](https://github.com/ceci98). lo que sigue es mejorarlo.
